config/routes.rb
Rails.application.routes.draw do
  root "categories#index"

  # get 'categories', to: "categories#index"
  resources "categories" do
    resources "comments", only: :create
  end
  resources "photos" do
    resources "comments", only: :create
  end

  resources "comments", only: :destroy

  get "/search", to: "photos#search"
  get "/search_photos", to: "photos#search_photos"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # Validations
  validates :name, presence: true, uniqueness: true
  validates :description, length: { in: 5..200 }

  # Associations
  has_many :photos, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_one_attached :cover
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Validations
  validates :content, length: { in: 5..200 }

  # Associations
  belongs_to :commentable, polymorphic: true, counter_cache: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  # Validations
  validates :title, presence: true, uniqueness: true
  validates :description, length: { in: 5..200 }

  # Associations
  belongs_to :category, counter_cache: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show
    @photos = @category.photos
    @comments = @category.comments
    @comment = Comment.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, status: :see_other
  end

  private

  def category_params
    params.require(:category).permit(:name, :description, :cover)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # POST photos/:photo_id/comments
  # POST categories/:category_id/comments
  def create
    if params[:photo_id]
      @commentable = Photo.find(params[:photo_id])
      @photo = @commentable
    elsif params[:category_id]
      @commentable = Category.find(params[:category_id])
      @category = @commentable
      @photos = @commentable.photos
    end

    @comments = @commentable.comments
    @comment = Comment.new(comment_params)
    @comment.commentable = @commentable

    if @comment.save
      redirect_to @commentable
    elsif params[:photo_id]
      render "photos/show", status: :unprocessable_entity
    elsif params[:category_id]
      render "categories/show", status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.commentable
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[show edit update destroy]

  def show
    @comments = @photo.comments
    @comment = Comment.new
  end

  def new
    @photo = Photo.new
    @category = Category.find(params[:category_id])
  end

  def create
    @photo = Photo.new(photo_params)
    @category = Category.find(@photo.category_id)
    if @photo.save
      redirect_to @photo.category
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @category = @photo.category
  end

  def update
    @category = Category.find(@photo.category_id)
    if @photo.update(photo_params)
      redirect_to @photo.category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category = @photo.category
    @photo.destroy
    redirect_to @category, status: :see_other
  end

  def search
    render "search/search"
  end

  def search_photos
    search = params[:search].downcase
    @photos = Photo.where("LOWER(title) like ?", "%#{search}%")
    render "search/search"
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :category_id, :image)
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <% category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <% category.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= f.label :cover %><br>
    <%= f.file_field :cover %>
    <% category.errors.full_messages_for(:cover).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render "form", category: @category %>
<%= link_to "Back", categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<%= link_to "New Category", new_category_path %>
<% @categories.each do |category| %>
  <div>
    <div>
      <% if category.cover.attached? %>
        <%= image_tag category.cover, alt:"#{category.name}" %>
      <% end %>
    </div>
    <h2><%= category.name %></h2>
    <span><%= category.photos_count%></span><br>
    <p><%= category.description %></p>
    <%= link_to "Show", category_path(category) %>
    <%= link_to "Edit", edit_category_path(category) %>
    <%= link_to "Delete", category_path(category), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </div>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render "form", category: @category %>
<%= link_to "Back", categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<p><%= @category.description %></p>
<%= link_to "New photo", new_photo_path(category_id: @category.id) %>
<% @photos.each do |photo| %>
  <%= render "photos/photo", photo: photo %> <br>
<% end %>
<div>
  <%= render "comments/form", comment: @comment, commentable: @category %>
</div>
<div>
  <h3>Comments</h3>
  <% @comments.each do |comment| %>
    <%= render "comments/comment", comment: comment %>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<div>
  <hr>
  <p>
    <%= comment.content %>
  </p>
  <p>
    Send <%= comment.created_at.strftime("%d-%m-%Y") %>
  </p>

  <%= button_to "Delete", comment, method: :delete %>
</div>

app/views/comments/_form.html.erb
<%= form_with model:[commentable, comment] do |f| %>
  <%= f.text_area :content, placeholder: "Some respecful comment here." %><br>
  <% comment.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Somesplash</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= image_tag "header.png" %> <br>
      <%= link_to "Search", search_path %>
      <hr>
    </header>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with model: photo do |f| %>
<div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <% photo.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <% photo.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, { selected: category.id } %>
    <% photo.errors.full_messages_for(:category_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% category.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div>
  <div>
    <% if photo.image.attached? %>
      <%= image_tag photo.image, alt: "#{photo.title}" %>
    <% end %>
  </div>
  <h2><%= photo.title %></h2>
  <p><span><%= photo.comments.count %> comments</span></p>
  <%= link_to "Show", photo_path(photo) %>
  <%= link_to "Edit", edit_photo_path(photo) %>
  <%= link_to "Delete", photo_path(photo), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>
</div>

app/views/photos/edit.html.erb
<h1>Edit photo</h1>
<%= render "form", photo: @photo ,category: @category %>

app/views/photos/new.html.erb
<h1>New Photo</h1>
<%= render "form", photo: @photo, category: @category %>

app/views/photos/show.html.erb
<div>
  <h1><%= @photo.title %></h1>
  <p><%= @photo.description %></p>
  <p><span>Updated at <%= @photo.updated_at.strftime("%B %d, %Y") %></span></p>
</div>
<div>
  <%= render "comments/form", comment: @comment, commentable: @photo %>
</div>
<div>
  <h3>Commnets</h3>
  <% @comments.each do |comment| %>
    <%= render "comments/comment", comment: comment %>
  <% end %>
</div>

app/views/search/search.html.erb
<h1>Search</h1>
<%= form_with url: "/search_photos", method: :get do |f| %>
  <%= f.text_field :search, placeholder: "Search term", required: true %> <br>
  <%= f.submit "Search Photos" %>
<% end %>
<% unless @photos.nil? %>
  <p>
    <%= "#{@photos.size} #{"photo".pluralize(@photos.size)} found" %>
  </p>
  <% @photos.each do |photo| %>
    <%= render "photos/photo", photo: photo %>
  <% end %>
<% end %>